dotnet test /p:AltCover=true /p:AltCoverThreshold=90 /p:AltCoverAssemblyExcludeFilter="NUnit|Microsoft|xunit|AltCover" /p:AltCoverTypeFilter="AutoGeneratedProgram" /p:AltCoverForce=true /p:AltCoverLocalSource=true
$reportGenVersion = "4.2.19";
$reportGen = "$env:UserProfile\.nuget\packages\reportgenerator\$reportGenVersion\tools\netcoreapp2.1\ReportGenerator.dll";
Start-Process dotnet -ArgumentList "$reportGen","-reports:./test/**/coverage.xml","-targetdir:.\test\artifacts","-reporttypes:MHTML;Badges" -NoNewWindow;